import type { RecommendationCandidate } from "@/lib/recsys/types";

/**
 * Curated development catalog — not production API data.
 * Each item has a real public source URL the user can open.
 * Images are optional Unsplash references used as visual stand-ins;
 * cards always have a CSS visual fallback via visualKey.
 */
export const SEED_CATALOG: RecommendationCandidate[] = [
  {
    slug: "saul-bass-titles",
    title: "Saul Bass title sequences",
    description:
      "Typography that performs the plot before a single scene — motion as narrative structure, not decoration.",
    sourceUrl: "https://www.artofthetitle.com/designer/saul-bass/",
    sourceName: "Art of the Title",
    imageUrl:
      "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=900&q=80",
    visualKey: "cinematic",
    category: "Typography",
    medium: "Film",
    tags: ["title sequence", "typography", "motion", "narrative"],
    aesthetics: ["Cinematic", "Editorial", "Minimal"],
    concepts: ["kinetic-type", "music-as-structure", "reduction"],
    popularity: 0.86,
    origin: "seed",
  },
  {
    slug: "enter-the-void-titles",
    title: "Enter the Void opening titles",
    description:
      "Neon type that behaves like a strobe — useful when an interface needs to feel like a night, not a form.",
    sourceUrl: "https://www.artofthetitle.com/title/enter-the-void/",
    sourceName: "Art of the Title",
    imageUrl:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=900&q=80",
    visualKey: "maximalist",
    category: "Motion",
    medium: "Film",
    tags: ["neon", "typography", "motion", "music"],
    aesthetics: ["Maximalist", "Experimental", "Cinematic"],
    concepts: ["kinetic-type", "audio-reactive", "immersion"],
    popularity: 0.72,
    origin: "seed",
  },
  {
    slug: "japanese-editorial-annuals",
    title: "Japanese graphic design annuals",
    description:
      "Asymmetric grids and dense type that still breathe. A layout language for discovery, not dashboards.",
    sourceUrl: "https://www.itsnicethat.com/features/japanese-graphic-design",
    sourceName: "It's Nice That",
    imageUrl:
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=900&q=80",
    visualKey: "editorial",
    category: "Typography",
    medium: "Editorial",
    tags: ["editorial", "typography", "asymmetric", "print"],
    aesthetics: ["Editorial", "Experimental", "Swiss"],
    concepts: ["asymmetric-layout", "dense-type", "vertical-rhythm"],
    popularity: 0.78,
    origin: "seed",
  },
  {
    slug: "the-line-music-magazine",
    title: "Editorial music magazines",
    description:
      "How print treats listening as a visual act — photography, type, and pacing as a browsing model.",
    sourceUrl: "https://www.itsnicethat.com/features/music-editorial-design",
    sourceName: "It's Nice That",
    imageUrl:
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=900&q=80",
    visualKey: "editorial",
    category: "Editorial",
    medium: "Editorial",
    tags: ["music", "editorial", "photography", "layout"],
    aesthetics: ["Editorial", "Cinematic", "Soft"],
    concepts: ["music-as-structure", "visual-discovery", "pacing"],
    popularity: 0.64,
    origin: "seed",
  },
  {
    slug: "experimental-music-interfaces",
    title: "Experimental music interfaces",
    description:
      "Players that treat a catalog as a landscape. Navigation through mood, not metadata.",
    sourceUrl: "https://www.awwwards.com/websites/music/",
    sourceName: "Awwwards",
    imageUrl:
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=900&q=80",
    visualKey: "futuristic",
    category: "UX",
    medium: "Websites",
    tags: ["music", "ux", "navigation", "visualization"],
    aesthetics: ["Experimental", "Futuristic", "Minimal"],
    concepts: ["visual-discovery", "spatial-nav", "audio-reactive"],
    popularity: 0.7,
    origin: "seed",
  },
  {
    slug: "audio-reactive-sketches",
    title: "Audio-reactive generative sketches",
    description:
      "Form that listens. Useful when a product should feel alive to sound rather than merely display it.",
    sourceUrl: "https://openprocessing.org/",
    sourceName: "OpenProcessing",
    imageUrl:
      "https://images.unsplash.com/photo-1614149162883-504ce4d13909?w=900&q=80",
    visualKey: "generative",
    category: "Creative Coding",
    medium: "Generative Art",
    tags: ["generative", "music", "motion", "code"],
    aesthetics: ["Experimental", "Futuristic"],
    concepts: ["audio-reactive", "generative-form", "music-as-structure"],
    popularity: 0.61,
    origin: "seed",
  },
  {
    slug: "ryoji-ikeda-data",
    title: "Ryoji Ikeda data installations",
    description:
      "Information as atmosphere. Dense, monochrome, and spatial — a model for visualizing catalogs without charts.",
    sourceUrl: "https://www.ryojiikeda.com/",
    sourceName: "Ryoji Ikeda",
    imageUrl:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=900&q=80",
    visualKey: "monochrome",
    category: "Data Visualization",
    medium: "Art",
    tags: ["data", "sound", "installation", "monochrome"],
    aesthetics: ["Monochrome", "Minimal", "Futuristic"],
    concepts: ["information-as-space", "audio-reactive", "reduction"],
    popularity: 0.69,
    origin: "seed",
  },
  {
    slug: "motion-as-navigation",
    title: "Motion as a navigation mechanism",
    description:
      "Transitions that carry meaning. The user doesn’t tap through pages — they move through states.",
    sourceUrl: "https://www.awwwards.com/websites/animation/",
    sourceName: "Awwwards",
    imageUrl:
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=900&q=80",
    visualKey: "experimental",
    category: "UX",
    medium: "Motion",
    tags: ["motion", "navigation", "ux", "transition"],
    aesthetics: ["Experimental", "Futuristic"],
    concepts: ["spatial-nav", "kinetic-type", "state-as-motion"],
    popularity: 0.74,
    origin: "seed",
  },
  {
    slug: "studio-dumbar-kinetic",
    title: "Studio Dumbar kinetic identities",
    description:
      "Logos that behave. Identity as a system of motion rather than a locked mark.",
    sourceUrl: "https://studiodumbar.com/",
    sourceName: "Studio Dumbar",
    imageUrl:
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=900&q=80",
    visualKey: "swiss",
    category: "Branding",
    medium: "Motion",
    tags: ["identity", "motion", "typography", "system"],
    aesthetics: ["Swiss", "Experimental"],
    concepts: ["kinetic-type", "system-thinking", "reduction"],
    popularity: 0.58,
    origin: "seed",
  },
  {
    slug: "typewolf-editorial-pairings",
    title: "Editorial type pairings on the web",
    description:
      "Serif display against quiet sans. A vocabulary for products that want to feel published, not shipped.",
    sourceUrl: "https://www.typewolf.com/",
    sourceName: "Typewolf",
    imageUrl:
      "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=900&q=80",
    visualKey: "editorial",
    category: "Typography",
    medium: "Typography",
    tags: ["typography", "editorial", "web", "pairing"],
    aesthetics: ["Editorial", "Swiss", "Minimal"],
    concepts: ["dense-type", "vertical-rhythm", "published-feel"],
    popularity: 0.81,
    origin: "seed",
  },
  {
    slug: "fonts-in-use-music",
    title: "Type on record sleeves",
    description:
      "How music packaging compresses a world into a square. Hierarchy under constraint.",
    sourceUrl: "https://fontsinuse.com/tags/1241/album-art",
    sourceName: "Fonts In Use",
    imageUrl:
      "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=900&q=80",
    visualKey: "retro",
    category: "Typography",
    medium: "Music",
    tags: ["typography", "music", "packaging", "constraint"],
    aesthetics: ["Editorial", "Retro", "Brutalist"],
    concepts: ["music-as-structure", "dense-type", "iconography"],
    popularity: 0.66,
    origin: "seed",
  },
  {
    slug: "autechre-sleeves",
    title: "Autechre sleeve systems",
    description:
      "Abstract packaging that refuses illustration. A way to represent sound without depicting instruments.",
    sourceUrl: "https://www.thedesignersrepublic.com/",
    sourceName: "The Designers Republic",
    imageUrl:
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=900&q=80",
    visualKey: "experimental",
    category: "Branding",
    medium: "Music",
    tags: ["music", "abstraction", "identity", "packaging"],
    aesthetics: ["Experimental", "Futuristic", "Monochrome"],
    concepts: ["abstraction", "music-as-structure", "system-thinking"],
    popularity: 0.55,
    origin: "seed",
  },
  {
    slug: "casa-da-musica",
    title: "OMA — Casa da Música",
    description:
      "A concert hall as a faceted object. Circulation, light, and volume as UX for a building — and maybe an app.",
    sourceUrl: "https://www.oma.com/projects/casa-da-musica",
    sourceName: "OMA",
    imageUrl:
      "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=900&q=80",
    visualKey: "architecture",
    category: "Architecture",
    medium: "Architecture",
    tags: ["architecture", "music", "circulation", "form"],
    aesthetics: ["Brutalist", "Futuristic", "Industrial"],
    concepts: ["spatial-nav", "circulation", "music-as-structure"],
    popularity: 0.63,
    origin: "seed",
  },
  {
    slug: "tadao-ando-light",
    title: "Tadao Ando — light as material",
    description:
      "Concrete, void, and a single slit of sun. Restraint that still feels emotional.",
    sourceUrl: "https://www.tadao-ando.com/",
    sourceName: "Tadao Ando",
    imageUrl:
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=900&q=80",
    visualKey: "minimal",
    category: "Architecture",
    medium: "Architecture",
    tags: ["architecture", "light", "concrete", "minimal"],
    aesthetics: ["Minimal", "Monochrome", "Industrial"],
    concepts: ["reduction", "void", "atmosphere"],
    popularity: 0.77,
    origin: "seed",
  },
  {
    slug: "airport-wayfinding",
    title: "Airport wayfinding systems",
    description:
      "Wayfinding under stress. Color, type, and sequence that must work at a glance — a lesson for any dense product.",
    sourceUrl: "https://www.pentagram.com/work",
    sourceName: "Pentagram",
    imageUrl:
      "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=900&q=80",
    visualKey: "swiss",
    category: "UX",
    medium: "Architecture",
    tags: ["wayfinding", "signage", "ux", "typography"],
    aesthetics: ["Swiss", "Industrial", "Minimal"],
    concepts: ["information-as-space", "hierarchy", "circulation"],
    popularity: 0.6,
    origin: "seed",
  },
  {
    slug: "tokyo-metro-diagrams",
    title: "Tokyo metro diagram language",
    description:
      "A network made legible without becoming a map. Color coding as navigation, not decoration.",
    sourceUrl: "https://www.tokyometro.jp/en/subwaymap/",
    sourceName: "Tokyo Metro",
    imageUrl:
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=900&q=80",
    visualKey: "swiss",
    category: "UX",
    medium: "Editorial",
    tags: ["diagram", "color", "navigation", "system"],
    aesthetics: ["Swiss", "Minimal"],
    concepts: ["information-as-space", "color-as-nav", "network"],
    popularity: 0.71,
    origin: "seed",
  },
  {
    slug: "wolfgang-tillmans",
    title: "Wolfgang Tillmans stills",
    description:
      "Casual frames that feel like looking. A photography grammar for products that want intimacy over polish.",
    sourceUrl: "https://tillmans.co.uk/",
    sourceName: "Wolfgang Tillmans",
    imageUrl:
      "https://images.unsplash.com/photo-1493863641943-9b68992a8d07?w=900&q=80",
    visualKey: "soft",
    category: "Photography",
    medium: "Photography",
    tags: ["photography", "editorial", "intimacy", "color"],
    aesthetics: ["Soft", "Editorial", "Organic"],
    concepts: ["intimacy", "found-composition", "color-mood"],
    popularity: 0.68,
    origin: "seed",
  },
  {
    slug: "film-stills-color",
    title: "Color palettes from film stills",
    description:
      "Grade as identity. Borrowing cinematic palettes for product worlds instead of generic UI blues.",
    sourceUrl: "https://filmschoolrejects.com/cinematography/",
    sourceName: "Film stills",
    imageUrl:
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=900&q=80",
    visualKey: "cinematic",
    category: "Color",
    medium: "Film",
    tags: ["color", "film", "mood", "palette"],
    aesthetics: ["Cinematic", "Editorial"],
    concepts: ["color-mood", "atmosphere", "world-building"],
    popularity: 0.73,
    origin: "seed",
  },
  {
    slug: "id-magazine-spreads",
    title: "i-D magazine spreads",
    description:
      "Fashion editorial that collides type and photography. Useful when a feed needs attitude, not cards.",
    sourceUrl: "https://i-d.co/",
    sourceName: "i-D",
    imageUrl:
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900&q=80",
    visualKey: "fashion",
    category: "Fashion",
    medium: "Fashion",
    tags: ["fashion", "editorial", "typography", "photography"],
    aesthetics: ["Editorial", "Experimental", "Maximalist"],
    concepts: ["asymmetric-layout", "dense-type", "attitude"],
    popularity: 0.62,
    origin: "seed",
  },
  {
    slug: "brutalist-websites",
    title: "Brutalist web experiments",
    description:
      "Sites that refuse smoothness. A reminder that an interface can have texture, weight, and friction on purpose.",
    sourceUrl: "https://brutalistwebsites.com/",
    sourceName: "Brutalist Websites",
    imageUrl:
      "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=900&q=80",
    visualKey: "brutalist",
    category: "Web Design",
    medium: "Websites",
    tags: ["brutalism", "web", "typography", "experimental"],
    aesthetics: ["Brutalist", "Experimental", "Industrial"],
    concepts: ["friction", "raw-material", "anti-template"],
    popularity: 0.75,
    origin: "seed",
  },
  {
    slug: "max-bill-posters",
    title: "Max Bill / Swiss posters",
    description:
      "Geometry as communication. Grid, type, and a few shapes doing all of the work.",
    sourceUrl: "https://www.moma.org/artists/557",
    sourceName: "MoMA",
    imageUrl:
      "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=900&q=80",
    visualKey: "swiss",
    category: "Typography",
    medium: "Art",
    tags: ["swiss", "poster", "geometry", "typography"],
    aesthetics: ["Swiss", "Minimal"],
    concepts: ["reduction", "grid", "geometry"],
    popularity: 0.67,
    origin: "seed",
  },
  {
    slug: "dieter-rams-calculator",
    title: "Dieter Rams calculators",
    description:
      "Buttons as a type system. Hierarchy through size, not chrome — still a north star for dense controls.",
    sourceUrl: "https://www.vitsoe.com/us/about/good-design",
    sourceName: "Vitsœ",
    imageUrl:
      "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=900&q=80",
    visualKey: "minimal",
    category: "Product Design",
    medium: "Apps",
    tags: ["product", "minimal", "controls", "hierarchy"],
    aesthetics: ["Minimal", "Industrial", "Swiss"],
    concepts: ["reduction", "hierarchy", "honesty"],
    popularity: 0.8,
    origin: "seed",
  },
  {
    slug: "ps2-spatial-menus",
    title: "PlayStation 2 menu as space",
    description:
      "A dashboard that feels like a room. Depth, sound, and idle motion as orientation.",
    sourceUrl: "https://www.ign.com/articles/playstation-2-menu",
    sourceName: "Interface archive",
    imageUrl:
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=900&q=80",
    visualKey: "futuristic",
    category: "UI",
    medium: "Games",
    tags: ["games", "ui", "spatial", "sound"],
    aesthetics: ["Futuristic", "Playful"],
    concepts: ["spatial-nav", "idle-motion", "sound-ui"],
    popularity: 0.54,
    origin: "seed",
  },
  {
    slug: "hypertext-literature",
    title: "Hypertext literature interfaces",
    description:
      "Reading as branching. A model for discovery products that shouldn’t force a single path.",
    sourceUrl: "https://www.eastgate.com/catalog/Fiction.html",
    sourceName: "Eastgate",
    imageUrl:
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=900&q=80",
    visualKey: "editorial",
    category: "UX",
    medium: "Websites",
    tags: ["hypertext", "narrative", "navigation", "web"],
    aesthetics: ["Experimental", "Editorial"],
    concepts: ["non-linear", "visual-discovery", "pacing"],
    popularity: 0.48,
    origin: "seed",
  },
  {
    slug: "cartographic-interfaces",
    title: "Cartographic interfaces",
    description:
      "Maps that hide as much as they show. Zoom as a metaphor for moving through a catalog.",
    sourceUrl: "https://www.stamen.com/",
    sourceName: "Stamen",
    imageUrl:
      "https://images.unsplash.com/photo-1524661132064-ba19648a3847?w=900&q=80",
    visualKey: "organic",
    category: "Data Visualization",
    medium: "Websites",
    tags: ["maps", "data", "navigation", "color"],
    aesthetics: ["Organic", "Editorial"],
    concepts: ["visual-discovery", "zoom-as-nav", "information-as-space"],
    popularity: 0.59,
    origin: "seed",
  },
  {
    slug: "generative-type-tools",
    title: "Generative type tools",
    description:
      "Letters that are grown, not drawn. Variable axes as a creative material.",
    sourceUrl: "https://www.futurefonts.xyz/",
    sourceName: "Future Fonts",
    imageUrl:
      "https://images.unsplash.com/photo-1516383740770-fbcc5ccbece0?w=900&q=80",
    visualKey: "experimental",
    category: "Typography",
    medium: "Creative Coding",
    tags: ["typography", "generative", "tools", "variable"],
    aesthetics: ["Experimental", "Playful"],
    concepts: ["generative-form", "kinetic-type", "variable-systems"],
    popularity: 0.57,
    origin: "seed",
  },
  {
    slug: "zine-culture",
    title: "Zine culture layouts",
    description:
      "Cheap print, high intent. Collage, xerox, and handmade grids as an antidote to template UI.",
    sourceUrl: "https://www.printedmatter.org/",
    sourceName: "Printed Matter",
    imageUrl:
      "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=900&q=80",
    visualKey: "editorial",
    category: "Editorial",
    medium: "Editorial",
    tags: ["zine", "collage", "print", "diy"],
    aesthetics: ["Editorial", "Experimental", "Playful"],
    concepts: ["collage", "anti-template", "handmade"],
    popularity: 0.56,
    origin: "seed",
  },
  {
    slug: "chris-cunningham-videos",
    title: "Chris Cunningham music videos",
    description:
      "Bodies, machines, and sound fused. A reference for interfaces that should feel physical.",
    sourceUrl: "https://www.dazeddigital.com/music/article/chris-cunningham",
    sourceName: "Dazed",
    imageUrl:
      "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=900&q=80",
    visualKey: "cinematic",
    category: "Motion",
    medium: "Film",
    tags: ["music", "film", "body", "industrial"],
    aesthetics: ["Cinematic", "Industrial", "Surreal"],
    concepts: ["music-as-structure", "physicality", "unease"],
    popularity: 0.52,
    origin: "seed",
  },
  {
    slug: "lygia-clark",
    title: "Lygia Clark — geometric participation",
    description:
      "Sculpture the viewer completes. Interaction as folding, not clicking.",
    sourceUrl: "https://www.moma.org/artists/1143",
    sourceName: "MoMA",
    imageUrl:
      "https://images.unsplash.com/photo-1547891654-e66ed7ebb234?w=900&q=80",
    visualKey: "organic",
    category: "Art",
    medium: "Art",
    tags: ["sculpture", "geometry", "interaction", "participation"],
    aesthetics: ["Minimal", "Organic", "Soft"],
    concepts: ["participation", "folding", "geometry"],
    popularity: 0.5,
    origin: "seed",
  },
  {
    slug: "exhibition-wayfinding",
    title: "Immersive exhibition wayfinding",
    description:
      "Museums that sequence rooms like chapters. Pacing, darkness, and reveal as a product pattern.",
    sourceUrl: "https://www.designboom.com/tag/exhibition-design/",
    sourceName: "Designboom",
    imageUrl:
      "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=900&q=80",
    visualKey: "cinematic",
    category: "Interaction Design",
    medium: "Architecture",
    tags: ["exhibition", "pacing", "space", "light"],
    aesthetics: ["Cinematic", "Minimal"],
    concepts: ["pacing", "reveal", "circulation"],
    popularity: 0.53,
    origin: "seed",
  },
  {
    slug: "analog-synth-panels",
    title: "Analog synthesizer panel design",
    description:
      "Dense controls that remain learnable. Modules, color, and grouping as an alternative to nested menus.",
    sourceUrl: "https://www.perfectcircuit.com/",
    sourceName: "Perfect Circuit",
    imageUrl:
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=900&q=80",
    visualKey: "industrial",
    category: "UI",
    medium: "Music",
    tags: ["music", "controls", "modular", "hardware"],
    aesthetics: ["Industrial", "Retro", "Brutalist"],
    concepts: ["modularity", "direct-manipulation", "density"],
    popularity: 0.65,
    origin: "seed",
  },
  {
    slug: "paper-architecture",
    title: "Paper architecture models",
    description:
      "Structure reduced to folds and shadows. A way to think about hierarchy without pixels.",
    sourceUrl: "https://www.archdaily.com/tag/paper-architecture",
    sourceName: "ArchDaily",
    imageUrl:
      "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=900&q=80",
    visualKey: "soft",
    category: "Architecture",
    medium: "Architecture",
    tags: ["model", "paper", "structure", "shadow"],
    aesthetics: ["Soft", "Minimal", "Organic"],
    concepts: ["reduction", "folding", "shadow"],
    popularity: 0.49,
    origin: "seed",
  },
  {
    slug: "newspaper-information",
    title: "Dense newspaper information design",
    description:
      "How much can live on one surface. Columns, decks, and jump lines as a feed architecture.",
    sourceUrl: "https://www.spd.org/",
    sourceName: "SPD",
    imageUrl:
      "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=900&q=80",
    visualKey: "editorial",
    category: "Editorial",
    medium: "Editorial",
    tags: ["editorial", "density", "hierarchy", "news"],
    aesthetics: ["Editorial", "Swiss"],
    concepts: ["dense-type", "hierarchy", "scanning"],
    popularity: 0.58,
    origin: "seed",
  },
  {
    slug: "variable-identity-systems",
    title: "Variable identity systems",
    description:
      "Brands that flex with context. A pattern for products whose look should change with the content inside.",
    sourceUrl: "https://www.underconsideration.com/brandnew/",
    sourceName: "Brand New",
    imageUrl:
      "https://images.unsplash.com/photo-1558655146-d09347e92766?w=900&q=80",
    visualKey: "swiss",
    category: "Branding",
    medium: "Websites",
    tags: ["identity", "system", "variable", "brand"],
    aesthetics: ["Swiss", "Experimental", "Minimal"],
    concepts: ["variable-systems", "system-thinking", "context"],
    popularity: 0.64,
    origin: "seed",
  },
  {
    slug: "hand-type-specimens",
    title: "Hand-drawn type specimens",
    description:
      "Letterforms with friction. Contrast for a world of perfectly hinted webfonts.",
    sourceUrl: "https://www.letterformarchive.org/",
    sourceName: "Letterform Archive",
    imageUrl:
      "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=900&q=80",
    visualKey: "organic",
    category: "Typography",
    medium: "Typography",
    tags: ["typography", "hand", "specimen", "craft"],
    aesthetics: ["Organic", "Editorial", "Retro"],
    concepts: ["handmade", "friction", "letterform"],
    popularity: 0.51,
    origin: "seed",
  },
  {
    slug: "vinyl-as-iconography",
    title: "Vinyl covers as app iconography",
    description:
      "A 12-inch square that has to work across a room. Compression, symbol, and mood in one hit.",
    sourceUrl: "https://coverartarchive.org/",
    sourceName: "Cover Art Archive",
    imageUrl:
      "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=900&q=80",
    visualKey: "retro",
    category: "Branding",
    medium: "Music",
    tags: ["music", "icon", "packaging", "symbol"],
    aesthetics: ["Retro", "Maximalist", "Editorial"],
    concepts: ["iconography", "compression", "music-as-structure"],
    popularity: 0.6,
    origin: "seed",
  },
  {
    slug: "soft-ui-editorial-contrast",
    title: "Soft UI against editorial type",
    description:
      "Rounded chrome next to a newspaper headline. Tension between product UI and published voice.",
    sourceUrl: "https://www.awwwards.com/websites/ui/",
    sourceName: "Awwwards",
    imageUrl:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=900&q=80",
    visualKey: "soft",
    category: "UI",
    medium: "Apps",
    tags: ["ui", "editorial", "contrast", "type"],
    aesthetics: ["Soft", "Editorial", "Minimal"],
    concepts: ["contrast", "published-feel", "product-voice"],
    popularity: 0.55,
    origin: "seed",
  },
  {
    slug: "fashion-runway-pacing",
    title: "Runway pacing as UX",
    description:
      "Looks arrive, hold, and leave. A sequencing lesson for onboarding, feeds, and reveals.",
    sourceUrl: "https://www.vogue.com/fashion-shows",
    sourceName: "Vogue",
    imageUrl:
      "https://images.unsplash.com/photo-1558769132-cb1aea3c8565?w=900&q=80",
    visualKey: "fashion",
    category: "Fashion",
    medium: "Fashion",
    tags: ["fashion", "pacing", "sequence", "body"],
    aesthetics: ["Editorial", "Cinematic", "Maximalist"],
    concepts: ["pacing", "reveal", "sequence"],
    popularity: 0.47,
    origin: "seed",
  },
  {
    slug: "code-as-material",
    title: "Creative coding as material",
    description:
      "Sketches where the algorithm is the craft. Useful when a product should generate, not merely display.",
    sourceUrl: "https://editor.p5js.org/",
    sourceName: "p5.js",
    imageUrl:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=900&q=80",
    visualKey: "generative",
    category: "Creative Coding",
    medium: "Creative Coding",
    tags: ["code", "generative", "sketch", "system"],
    aesthetics: ["Experimental", "Playful", "Futuristic"],
    concepts: ["generative-form", "variable-systems", "craft"],
    popularity: 0.7,
    origin: "seed",
  },
];
